version: "3.9"

services:
  mdp-web-app:
    container_name: mdp-web-app
    build:
      context: ./NST-front
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - mdp-rest-app

  mdp-ai-app:
    container_name: mdp-ai-app
    build:
      context: ./MDP_NEURON
      dockerfile: Dockerfile-AI
    ports:
      - "8001:8001"
    depends_on:
      - mdp-rest-app

  mdp-rest-app:
    container_name: mdp-rest-app
    build:
      context: ./mdp-rest-server
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - mdp-db
    environment:
      - DB_HOST=mdp-db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=12345
      - DATABASE_URL=postgresql://postgres:12345@mdp-db:5432/postgres

  mdp-db:
    image: postgres:16
    container_name: mdp-db
    user: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12345
      - POSTGRES_DB=postgres
      - DATABASE_URL=postgresql://postgres:12345@mdp-db:5432/postgres
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./mdp-rest-server/init.sql/mdp-clear.sql:/docker-entrypoint-initdb.d/mdp-clear.sql
    ports:
      - "5432:5432"
    expose:
      - 5432
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db-data:
